# Generated by Django 3.1 on 2020-08-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200812_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notifications',
            field=models.JSONField(default={}),
        ),
    ]
