# Generated by Django 3.0.8 on 2020-07-23 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='slug',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('object_of_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Church')),
            ],
        ),
    ]
