# Generated by Django 3.1 on 2020-12-20 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_main_order_validation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'ordering': ('main_order',)},
        ),
        migrations.AddField(
            model_name='church',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=9),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('is_in_list', models.BooleanField(default=False)),
                ('season', models.CharField(choices=[('all', 'All seasons'), ('winter', 'Winter view'), ('spring', 'Spring view'), ('summer', 'Summer view'), ('autumn', 'Autumn/fall view')], default='all', max_length=100, null=True, verbose_name='Season when this photo is created')),
                ('tip_text', models.CharField(max_length=100)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church')),
            ],
        ),
    ]
